import { CalendarDays, CheckCircle2, Clock3, Compass, FileText, Layers3, Linkedin, Mail, ShieldCheck } from "lucide-react";

type Locale = "tr" | "en";

export function ResearchDeskSupplement({ locale }: { locale: Locale }) {
  const english = locale === "en";
  return <div className="module-supplement research-supplement"><section><span>{english ? "RESEARCH MAP" : "ARAŞTIRMA HARİTASI"}</span><h2>{english ? "Coverage before volume" : "Hacimden önce kapsama"}</h2><p>{english ? "Each future report can be positioned by company, theme, period and method without losing its source trail." : "Gelecek her rapor; şirket, tema, dönem ve yöntemle kaynak izini kaybetmeden konumlandırılabilir."}</p><div className="module-mini-list"><b><Compass size={14}/>{english ? "Company analysis" : "Şirket analizi"}</b><b><Layers3 size={14}/>{english ? "Sector notes" : "Sektör notları"}</b><b><FileText size={14}/>{english ? "Valuation framework" : "Değerleme çerçevesi"}</b></div></section><section><span>{english ? "PUBLICATION PROTOCOL" : "YAYIN PROTOKOLÜ"}</span><h2>{english ? "A repeatable report path" : "Tekrarlanabilir rapor akışı"}</h2><div className="protocol-lines"><p><CheckCircle2 size={14}/>{english ? "Source file is attached" : "Kaynak dosyası eklenir"}</p><p><CheckCircle2 size={14}/>{english ? "Method & period are stated" : "Yöntem ve dönem belirtilir"}</p><p><CheckCircle2 size={14}/>{english ? "Disclosure is visible" : "Açıklama görünür kalır"}</p></div></section><section><span>{english ? "LIBRARY RHYTHM" : "KÜTÜPHANE RİTMİ"}</span><h2>{english ? "Ready for the next upload" : "Yeni yüklemeye hazır"}</h2><p>{english ? "When a new PDF is supplied, it can be added with a clean card, searchable metadata and a direct open action." : "Yeni bir PDF sağlandığında temiz kart, aranabilir metadata ve doğrudan açma eylemiyle kütüphaneye eklenebilir."}</p><b className="module-status"><CalendarDays size={14}/>{english ? "Library status · ready" : "Kütüphane durumu · hazır"}</b></section></div>;
}

export function ContactDeskSupplement({ locale }: { locale: Locale }) {
  const english = locale === "en";
  return <div className="module-supplement contact-supplement"><section><span>{english ? "WORKING TOPICS" : "ÇALIŞMA KONULARI"}</span><h2>{english ? "Where a message can begin" : "Mesajın başlayabileceği yer"}</h2><div className="module-mini-list"><b><FileText size={14}/>{english ? "Research exchange" : "Araştırma paylaşımı"}</b><b><Compass size={14}/>{english ? "Academic project" : "Akademik proje"}</b><b><Layers3 size={14}/>{english ? "Valuation discussion" : "Değerleme konuşması"}</b></div></section><section><span>{english ? "RESPONSE PATH" : "YANIT AKIŞI"}</span><h2>{english ? "Clear and direct" : "Açık ve doğrudan"}</h2><div className="protocol-lines"><p><Mail size={14}/>{english ? "Draft opens in your email client" : "Taslak e-posta uygulamanda açılır"}</p><p><Clock3 size={14}/>{english ? "A concise subject keeps context clear" : "Kısa konu satırı bağlamı açık tutar"}</p><p><ShieldCheck size={14}/>{english ? "No form input is stored here" : "Form girdisi burada saklanmaz"}</p></div></section><section><span>{english ? "PROFESSIONAL CHANNEL" : "PROFESYONEL KANAL"}</span><h2>{english ? "LinkedIn profile" : "LinkedIn profili"}</h2><p>{english ? "For a concise professional introduction and project context, the LinkedIn channel remains available alongside email." : "Kısa profesyonel tanıtım ve proje bağlamı için LinkedIn kanalı e-postayla birlikte kullanılabilir."}</p><a className="module-status" href="https://www.linkedin.com/in/onur%C4%B1nal/" target="_blank" rel="noreferrer"><Linkedin size={14}/>{english ? "Open LinkedIn" : "LinkedIn’i Aç"}</a></section></div>;
}
